spring:
    application:
        name: hr-api-gateway
    cloud:
       gateway:
          discovery:
            locator:
                enabled: true
                lower-case-service-id: true
          routes:
           - id: hr-worker-route
             uri: lb://hr-worker
             predicates:
             - Path=/hr-worker/**
           - id: hr-payroll-route
             uri: lb://hr-payroll
             predicates:
              - Path=/hr-payroll/**
           - id: hr-user-route
             uri: lb://hr-user
             predicates:
              - Path=/hr-user/**

server:
    port: 8765

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka  
